name: paneuc
channels:
  - defaults
  - bioconda
  - conda-forge
  - r
dependencies:
  - python=3.*
  - snakemake
  - bwa
  - freebayes
  - vt
  - samtools
  - bcftools
  - bedops
  - qualimap
  - AdapterRemoval
  - seqhax
  - pigz
  - matplotlib =2.2
  - pandas =0.23
  - seaborn =0.8
  - r-rgl
  - r-devtools
  - rust
  - khmer
  - r-ggplot2
  - r-vcfr
