
samples: "metadata/sample2runlib.csv"

qc:
  _DEFAULT_:
    adapter1: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
    adapter2: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT
    minqual: 25
  LBEmel:
    adapter1: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
    adapter2: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT
    minqual: 25

sample_sets: []


refs:
  Sorghum: genomes_and_annotations/genomes/Sorghum/genome.fa


mapping:
  aligners:
    - bwa
  refs:
    - Sorghum
  samplesets:
    - all_samples
  ngm:
    sensitivity: 0.5


snpeff:
  name: Sorghum_bicolor_NCBIv3.42
  Sorghum: genomes_and_annotations/snpeffdata/genomes/Sorghum_bicolor_NCBIv3.42.fa.gz


denovodist:
  kwip_sketchsize: 1e9
  mash_sketchsize: 1e5
  sourmash_sketchsize: 1e5
  ksize: 21
  kwip_sets: [] 
  mash_sets: # we can subset from everything for (sour)mash
    - all_samples
  sourmash_sets: []

varcall:
  minmapq:
    bwa: 30
    ngm: 10
  minbq: 15
  theta_prior: 0.1 # approx 10% of sites vary, it seems. Crazy!
  chunksize: 1000000
  aligners:
    - bwa
  callers:
    #- mpileup
    - freebayes
  refs:
    - Sorghum
  samplesets:
    - all_samples
  filters:
    default: >
      -i 'QUAL >= 10 &&
          ALT != "." &&
          INFO/DP >= 5 &&
          INFO/AN >= 3'
    strict: >
      -i 'QUAL >= 40 &&
          ALT != "." &&
          INFO/DP >= 20 &&
          ((INFO/AN / N_SAMPLES)*2) > 0.20 &&
          MAF >= 0.01'
    # Above is presence rate, >20%
